# Enter your your username (or colloquial version) here. This is
#  used for quote fact outputs (ex// I use Capn for CapnCeedee)
colloquial_username: Capn
# A valid timezone from pytz
# Non-exhaustive list here: https://gist.github.com/heyalexej/8bf688fd67d7199be4a1682b3eec7568
timezone: America/Chicago